#!/bin/bash
#SBATCH --tasks-per-node=20                               # Request 1 cores
#SBATCH -N 1                               # Request one node (if you request more than one core with -c, also using
                                           # -N 1 means all cores will be on the same node)
#SBATCH -J cellranger                       #name job
#SBATCH -t 6-00:00                         # Runtime in D-HH:MM format
#SBATCH -A lu2022-2-4
#SBATCH -p lu
#SBATCH --mem-per-cpu=9500                  # Memory per cpu 200GB total
#SBATCH -o hostname_%j.out                 # File to which STDOUT will be written, including job ID
#SBATCH -e hostname_%j.err                 # File to which STDERR will be written, including job ID
#SBATCH --mail-type=ALL                    # Type of email notification- BEGIN,END,FAIL,ALL
#SBATCH --mail-user=me2152ba-s@student.lu.se   # Email to which notifications will be sent

#enter wd
cd /home/meghana/workspace/tools/

#load cellranger
#module load cellranger/6.0.0

#run cellranger
cellranger multi --id=Spleenocyte --csv=/home/meghana/workspace/cellplex/config.csv
